users/urls.py
from django.urls import path
from .views import SignUpView, CustomLoginView, ChangeProfileView
from django.contrib.auth.views import LogoutView


app_name = 'users'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', CustomLoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(next_page='index'), name='logout'),
    path('settings/', ChangeProfileView.as_view(), name='settings'),
]

users/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User


class UserProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='pictures/', blank=True)

    @property
    def image_url(self):
        if self.avatar:
            return self.avatar.url
        return settings.STATIC_URL + 'img/default.jpeg'

users/forms.py
from django import forms
from .models import UserProfile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import AuthenticationForm, UsernameField


class SignUpForm(UserCreationForm):

    username = forms.CharField(label='Login',
                               max_length=100,
                               widget=forms.TextInput(attrs={'class': 'form-control'}),
                               )

    email = forms.EmailField(label='Email',
                             max_length=100,
                             widget=forms.EmailInput(attrs={'class': 'form-control'}),
                             )

    password1 = forms.CharField(label=_("Password"),
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                                )
    password2 = forms.CharField(label=_("Password confirmation"),
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                                )

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)


class CustomAuthenticationForm(AuthenticationForm):

    username = UsernameField(label='Login',
                             widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control'}),
                             )
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                               )


class ChangeProfileForm(forms.ModelForm):

    email = forms.EmailField(label='Email',
                             max_length=100,
                             widget=forms.EmailInput(attrs={'class': 'form-control'}),
                             )

    class Meta:
        model = User
        fields = ('email',)


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('avatar',)

users/views.py
from django.shortcuts import render
from django.views.generic.base import View
from .forms import SignUpForm, UserProfileForm, CustomAuthenticationForm, ChangeProfileForm
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.db import transaction


class SignUpView(View):

    user_form = SignUpForm
    user_profile_form = UserProfileForm
    template_name = 'signup.html'

    def get(self, request):
        user_form = self.user_form()
        user_profile_form = self.user_profile_form()
        return render(request, self.template_name,
                      context={"user_form": user_form,
                               "user_profile_form": user_profile_form})

    @transaction.atomic()
    def post(self, request):
        user_form = self.user_form(request.POST)
        user_profile_form = self.user_profile_form(request.POST, request.FILES)
        if user_form.is_valid() and user_profile_form.is_valid():
            user_form.save()
            user_profile = user_profile_form.save(commit=False)
            user_profile.user_id = user_form.instance.id
            user_profile.save()
            username, password = user_form.cleaned_data.get('username'), user_form.cleaned_data.get('password1')
            new_user = authenticate(username=username, password=password)
            login(self.request, new_user)
            return redirect(reverse_lazy('index'))
        return render(request, self.template_name,
                      context={"user_form": user_form,
                               "user_profile_form": user_profile_form})


class CustomLoginView(LoginView):

    authentication_form = CustomAuthenticationForm
    template_name = 'login.html'


class ChangeProfileView(LoginRequiredMixin, View):

    user_form = ChangeProfileForm
    user_profile_form = UserProfileForm
    login_url = reverse_lazy('users:login')
    template_name = 'settings.html'

    def get(self, request):
        user_form = self.user_form(instance=request.user)
        user_profile_form = self.user_profile_form(instance=request.user.userprofile)
        return render(request, self.template_name,
                      context={"user_form": user_form,
                               "user_profile_form": user_profile_form})

    @transaction.atomic()
    def post(self, request):
        user_form = self.user_form(request.POST, instance=request.user)
        user_profile_form = self.user_profile_form(request.POST, request.FILES, instance=request.user.userprofile)
        if user_form.is_valid() and user_profile_form.is_valid():
            user_form.save()
            user_profile_form.save()
            return redirect(reverse_lazy('index'))
        return render(request, self.template_name,
                      context={"user_form": user_form,
                               "user_profile_form": user_profile_form})

users/templates/login.html
{% extends 'base.html' %}
{% block title %} Login - Hasker {% endblock %}
{% block content %}
    <div class="col-md-4 form-page">
        <p class="break"></p>
        <h5> Log in </h5>
        <p class="break"></p>
        <form method="post" enctype='multipart/form-data'>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-secondary btn-sm">Login</button>
        </form>
    </div>
{% endblock %}

users/templates/settings.html
{% extends 'base.html' %}
{% block title %} Settings - Hasker {% endblock title %}
{% block content %}
    <div class="col-md-4 form-page">
        <p class="break"></p>
        <h5> Settings </h5>
        <p class="break"></p>
        <form method="post" enctype='multipart/form-data'>
            {% csrf_token %}
            {{ user_form.as_p }}
            <p><label for="id_avatar">Avatar:</label>
            {% if user.userprofile.avatar %}
                <p><img src="{{ user.userprofile.image_url }}" width="100" height="100"></p>
            {% endif %}
            <p> Change: <input type="file" name="avatar" accept="image/*" id="id_avatar"></p>
            <button type="submit" class="btn btn-secondary btn-sm">Submit</button>
        </form>
    </div>
{% endblock %}

users/templates/signup.html
{% extends 'base.html' %}
{% block title %} Sign Up - Hasker {% endblock title %}
{% block content %}
    <div class="col-md-4 form-page">
        <p class="break"></p>
        <h5> Sign Up </h5>
        <p class="break"></p>
        <form method="post" enctype='multipart/form-data'>
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ user_profile_form.as_p }}
            <button type="submit" class="btn btn-secondary btn-sm">Submit</button>
        </form>
    </div>
{% endblock %}