questions/urls.py
from django.urls import path
from .views import IndexView, AskQuestionView, QuestionView, VoteView, MarkCorrectAnswerView, SearchResultsView


app_name = 'questions'
urlpatterns = [
    path('order_by/<str:orderby>', IndexView.as_view(), name='index'),
    path('new/', AskQuestionView.as_view(), name='ask'),
    path('question/<int:pk>/', QuestionView.as_view(), name='question'),
    path('vote_up_<str:object_type>_<int:obj_id>/', VoteView.as_view(vote_up=True), name='vote_up'),
    path('vote_down_<str:object_type>_<int:obj_id>/', VoteView.as_view(vote_up=False), name='vote_down'),
    path('mark_<int:answer_id>_<int:question_id>/', MarkCorrectAnswerView.as_view(), name='correct_answer'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
]

users/urls.py
from django.urls import path
from .views import SignUpView, CustomLoginView, ChangeProfileView
from django.contrib.auth.views import LogoutView


app_name = 'users'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', CustomLoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(next_page='index'), name='logout'),
    path('settings/', ChangeProfileView.as_view(), name='settings'),
]

questions/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse


class Question(models.Model):

    header = models.TextField(max_length=300, verbose_name='title')
    body = models.TextField(max_length=1000)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_date = models.DateTimeField(default=timezone.now)
    tags = models.ManyToManyField('Tag', related_name='questions', blank=True)
    answers = models.IntegerField(default=0)
    votes = models.IntegerField(default=0)
    users_voted_up = models.ManyToManyField(User, related_name='questions_voted_up', blank=True)
    users_voted_down = models.ManyToManyField(User, related_name='questions_voted_down', blank=True)
    correct_answer = models.OneToOneField('Answer',
                                          on_delete=models.SET_NULL,
                                          null=True,
                                          related_name='correct_answer_set')

    class Meta:
        ordering = ['-votes', '-created_date']

    def __str__(self):
        return self.header

    def get_absolute_url(self):
        return reverse('questions:question', kwargs={'pk': self.pk})

    def get_tags(self):
        return [tag.tag_text for tag in self.tags.all()]


class Tag(models.Model):

    tag_text = models.TextField(null=True)

    def __str__(self):
        return self.tag_text


class Answer(models.Model):

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    body = models.TextField(verbose_name='your answer')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_date = models.DateTimeField(default=timezone.now)
    votes = models.IntegerField(default=0)
    users_voted_up = models.ManyToManyField(User, related_name='answers_voted_up', blank=True)
    users_voted_down = models.ManyToManyField(User, related_name='answers_voted_down', blank=True)

    class Meta:
        ordering = ['-votes', '-created_date']

    def __str__(self):
        return self.body

questions/forms.py
from django import forms
from .models import Question, Answer
from django.utils.translation import ugettext_lazy as _


class AskQuestionForm(forms.ModelForm):

    tags = forms.CharField(required=False,
                           label='Tags',
                           help_text=_('Add up to 3 tags to describe what your question is about'),
                           widget=forms.Textarea(attrs={'placeholder': 'e.g. tag1, tag2, tag3',
                                                        'class': 'form-control', 'rows': 1}),
                           )

    class Meta:
        model = Question
        fields = ('header', 'body',)
        help_texts = {
            'header': _('Be specific and imagine you’re asking a question to another person'),
            'body': _('Include all the information someone would need to answer your question')
        }
        widgets = {
            'header': forms.Textarea(attrs={'placeholder': 'e.g. How to python',
                                            'class': 'form-control', 'rows': 1}),
            'body': forms.Textarea(attrs={'class': 'form-control', 'rows': 8}),
        }

    def clean_tags(self):
        data = self.cleaned_data['tags']
        if not data:
            tags = []
        else:
            tags = [val.strip() for val in data.split(',') if len(val.strip()) > 0]
        if len(tags) > 3:
            raise forms.ValidationError(_("Enter three tags or less"))
        return tags


class AnswerForm(forms.ModelForm):

    class Meta:
        model = Answer

        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control', 'rows': 8}),
        }

questions/views.py
from django.views.generic.base import View
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, FormView
from .forms import AskQuestionForm, AnswerForm
from .models import Question, Answer, Tag
from django.db.models import Q
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.core.mail import send_mail
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from django.db import transaction


class AskQuestionView(LoginRequiredMixin, CreateView):

    form_class = AskQuestionForm
    model = Question
    login_url = reverse_lazy('users:login')
    template_name = 'ask_question.html'

    @transaction.atomic()
    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        tags = form.cleaned_data.get('tags')
        tags_objects = [Tag.objects.get_or_create(tag_text=tag)[0] for tag in tags]
        form.instance.tags.add(*tags_objects)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('questions:question', kwargs={'pk': self.object.id})


class QuestionView(ListView, FormView):

    paginate_by = 20
    form_class = AnswerForm
    context_object_name = 'answers'
    template_name = 'question.html'

    def get_queryset(self):
        return Answer.objects.filter(question=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = AnswerForm()
        context['question'] = get_object_or_404(Question, pk=self.kwargs['pk'])
        return context

    def send_notification(self, question):
        email_header = 'New answer'
        email_body = '''You've got new answer: '''
        send_mail(
            email_header,
            "".join([email_body, self.request.build_absolute_uri(question.get_absolute_url())]),
            settings.EMAIL_HOST_USER,
            [question.user.email],
            fail_silently=False)

    @transaction.atomic()
    def form_valid(self, form):
        question = get_object_or_404(Question, pk=self.kwargs['pk'])
        form.instance.user = self.request.user
        form.instance.question = question
        form.instance.answers = question.answers + 1
        form.save()
        self.send_notification(question)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('questions:question', kwargs={'pk': self.kwargs['pk']})


class IndexView(ListView):

    model = Question
    paginate_by = 30
    template_name = 'index.html'

    def get_ordering(self):
        ordering = self.kwargs.get('orderby', '-created_date')
        return ordering


class VoteView(LoginRequiredMixin, View):

    login_url = reverse_lazy('users:login')
    vote_up = False

    def get(self, request, *args, **kwargs):
        objects = {
            'answer': Answer,
            'question': Question,
        }
        object_type = self.kwargs.get('object_type')
        obj_id = self.kwargs.get('obj_id')
        vote_up = self.vote_up
        request_object = get_object_or_404(objects[object_type], pk=obj_id)
        question = request_object if object_type == 'question' else request_object.question
        already_voted_up = request_object.users_voted_up.filter(id=self.request.user.id).exists()
        already_voted_down = request_object.users_voted_down.filter(id=self.request.user.id).exists()
        if vote_up:
            if already_voted_down:
                request_object.votes += 1
                request_object.users_voted_down.remove(self.request.user)
            elif not already_voted_up:
                request_object.votes += 1
                request_object.users_voted_up.add(self.request.user)
        else:
            if already_voted_up:
                request_object.votes -= 1
                request_object.users_voted_up.remove(self.request.user)
            elif not already_voted_down:
                request_object.votes -= 1
                request_object.users_voted_down.add(self.request.user)
        request_object.save()
        return redirect(reverse_lazy('questions:question', kwargs={'pk': question.id}))


class MarkCorrectAnswerView(LoginRequiredMixin, View):

    login_url = reverse_lazy('users:login')

    def get(self, request, *args, **kwargs):
        question = get_object_or_404(Question, pk=self.kwargs.get('question_id'))
        if question.user == request.user:
            answer = get_object_or_404(Answer, pk=self.kwargs.get('answer_id'))
            if question.correct_answer == answer:
                question.correct_answer = None
            else:
                question.correct_answer = answer
            question.save()
        return redirect(reverse_lazy('questions:question', kwargs={'pk': question.id}))


class SearchResultsView(ListView):

    model = Question
    template_name = 'search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q').strip()
        if query.startswith('tag:'):
            query = query.replace('tag:', '').strip()
            object_list = Question.objects.filter(tags__tag_text=query)
        else:
            object_list = Question.objects.filter(
                Q(header__icontains=query) | Q(body__icontains=query)
            )
        return object_list

questions/templates/_answer_form.html
<div class="row justify-content-center">
    <div class="col-md-10">
        <form method="post" enctype='multipart/form-data' novalidate>
            {% csrf_token %}
            {{ form.as_p}}
            <button type="submit" class="btn btn-secondary btn-sm">Submit</button>
        </form>
    </div>
</div>

questions/templates/_pagination.html
{% block pagination %}
  {% if is_paginated %}
    <div class="row justify-content-center">
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>
      </div>
    </div>
  {% endif %}
{% endblock %}

questions/templates/_questions_list.html
{% load humanize %}
<div class="col-md-9 float-left ">
    <div class="row justify-content-center">
        <div class="col-8">
            <table class="table table-borderless">
                {% for question in object_list %}
                    <tr height="90%">
                        <td class="align-middle" rowspan="2" width="5%"><p class="text-center">{{ question.votes }}</p><p>Vote{{ question.votes|pluralize }}</p></td>
                        <td class="align-middle" rowspan="2" width="5%"><p class="text-center">{{ question.answers }}</p><p>Answer{{ question.answers|pluralize }}</p></td>
                        <td width="60%" colspan="2"><h5><a href="{% url 'questions:question' question.id %}">{{ question.header }}</a></h5></td>
                    </tr>
                    <tr>
                        <td>
                            {% for tag in question.get_tags %}
                                <a class="btn btn-secondary btn-sm" href="{% url 'questions:search_results' %}?q=tag:{{tag}}" role="button"> {{ tag }} </a>
                            {% endfor %}
                        </td>
                        <td class="text-right text-small">Asked {{question.created_date|naturaltime}} {{ question.user }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    {% include '_pagination.html' with form=form %}
    <p class="break"></p>
</div>

questions/templates/ask_question.html
{% extends 'base.html' %}
{% block title %} Ask - Hasker {% endblock title %}
{% block content %}
    <div class="col-md-9">
        <p class="break"></p>
        <h5> Ask a question </h5>
        <p class="break"></p>
        <div class="col-md-10">
            <form method="post" enctype='multipart/form-data' novalidate>
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-secondary btn-sm">Submit</button>
            </form>
        </div>
    </div>
{% endblock content %}

questions/templates/index.html
{% extends 'base.html' %}
{% block title %} Questions - Hasker {% endblock title %}
{% block content %}
    <ul class="nav justify-content-center">
        <li class="nav-item">
            <h5><a class="nav-link text-large {% if request.resolver_match.kwargs.orderby == '-created_date' %}disabled{% endif %}"
               href="{% url 'questions:index' '-created_date' %}">New questions<span class="sr-only">(current)</span>
            </a></h5>
        </li>
        <li class="nav-item">
            <h5><a class="nav-link text-large {% if request.resolver_match.kwargs.orderby == '-votes' %}disabled{% endif %}"
               href="{% url 'questions:index' '-votes' %}">Hot questions <span class="sr-only">(current)</span>
            </a></h5>
        </li>
    </ul>
    <p class="break-large"></p>
{% include '_questions_list.html' %}
{% endblock content %}

questions/templates/question.html
{% extends 'base.html' %}]
{% load humanize %}
{% block title %} {{question.header}} - Hasker {% endblock title %}
{% block content %}
    <div class="col-md-8 float-left">
        <p class="break"></p>
        <h4> {{question.header}} </h4>
        <p class="break"></p>

        <div class="row justify-content-center">
            <p class="break"></p>
            <table class="table table-borderless">
                <tr height="90%">
                    <td class="align-top" rowspan="2" width="10%">
                        <p class="text-center">
                            {% if user.is_authenticated %}
                                <a class="arrow up" title="Like this question" href="{% url 'questions:vote_up' 'question' question.id %}"></a>
                            {% else %}
                                <a class="arrow up not-active" title="Like this question" href="{% url 'questions:vote_up' 'question' question.id %}"></a>
                            {% endif %}
                        </p>
                        <p class="text-center"> {{ question.votes }} </p>
                        <p class="text-center">
                            {% if user.is_authenticated %}
                                <a class="arrow down" title="Don't like this question" href="{% url 'questions:vote_down' 'question' question.id %}"></a>
                            {% else %}
                                <a class="arrow down not-active" title="Like this question" href="{% url 'questions:vote_down' 'question' question.id %}"></a>
                            {% endif %}
                        </p>
                    </td>
                    <td colspan="4"> {{ question.body }} </td>
                </tr>
                <tr>
                    <td width="40%">
                        {% for tag in question.tags.all %}
                            <a class="btn btn-secondary btn-sm" href="{% url 'questions:search_results' %}?q=tag:{{tag}}" role="button"> {{ tag.tag_text }} </a>
                        {% endfor %}
                    </td>
                    <td><p class="text-right text-small"> Asked {{question.created_date|naturaltime}} </p></td>
                    <td width="5%"> <img src="{{ question.user.userprofile.image_url }}" width="30" height="30"> </td>
                    <td width="5%"> {{ question.user }} </td>
                    <td width="10%"></td>
                </tr>
            </table>
        </div>

        <p class="break"></p>
        <h5> {{question.answers}} Answers </h5>
        <p class="break"></p>

        <div class="row justify-content-center">
            <p class="break"></p>
            <table class="table table-borderless">
            {% for answer in object_list %}
                <tr height="90%">
                    <td class="align-top" rowspan="2"  width="10%">
                        <p class="text-center">
                            {% if user.is_authenticated %}
                                <a class="arrow up" title="Like this answer" href="{% url 'questions:vote_up' 'answer' answer.id %}"></a>
                            {% else %}
                                <a class="arrow up not-active" title="Like this answer" href="{% url 'questions:vote_up' 'answer' answer.id %}"></a>
                            {% endif %}
                        </p>
                        <p class="text-center">{{ answer.votes }}</p>
                        <p class="text-center">
                            {% if user.is_authenticated %}
                                <a class="arrow down" title="Don't like this answer" href="{% url 'questions:vote_down' 'answer' answer.id %}"></a>
                            {% else %}
                                <a class="arrow down not-active" title="Don't like this answer" href="{% url 'questions:vote_down' 'answer' answer.id %}"></a>
                            {% endif %}
                        </p>
                        <p class="text-center">
                            {% if user.is_authenticated %}
                                <a title="This answer is correct!" href="{% url 'questions:correct_answer' answer_id=answer.id question_id=question.id %}">
                                {% if answer.id == question.correct_answer.id %} &#9733;
                                {% else %}
                                    {% if question.user == user %}
                                        &#9734;
                                    {% endif %}
                                {% endif %}
                                </a>
                            {% elif  answer.id == question.correct_answer.id %}
                                <a class="not-active" title="This answer is correct!" href="{% url 'questions:correct_answer' answer_id=answer.id question_id=question.id %}">
                                &#9733;
                                </a>
                            {% endif %}
                        </p>
                    </td>
                    <td colspan="4"> {{ answer.body }} </td>
                </tr>
                <tr>
                    <td width="40%"></td>
                    <td><p class="text-right text-small"> Answered {{answer.created_date|naturaltime}} </p></td>
                    <td width="5%"> <img src="{{ answer.user.userprofile.image_url }}" width="30" height="30"> </td>
                    <td width="5%"><p class="text-small"> {{ answer.user }} </p></td>
                    <td width="10%"></td>
                </tr>
                <tr class="border_bottom">
                    <td colspan="4"></td>
                </tr>
            {% endfor %}
            </table>
        </div>
        {% include '_pagination.html' with form=form %}
        <p class="break"></p>
        {% if user.is_authenticated %}
            {% include '_answer_form.html' with form=form %}
        {% endif %}
    </div>
{% endblock content %}

questions/templates/search_results.html
{% extends 'base.html' %}
{% block title %} Search results - Hasker {% endblock title %}
{% block content %}
    <div class="col-md-4 form-page">
        <p class="break"></p>
        <h5>Search Results</h5>
        <p class="break"></p>
    </div>
{% include '_questions_list.html' %}
{% endblock content %}