questions/urls.py
from django.urls import path
from .views import IndexView, AskQuestionView, QuestionView, VoteView, MarkCorrectAnswerView, SearchResultsView


app_name = 'questions'
urlpatterns = [
    path('order_by/<str:orderby>', IndexView.as_view(), name='index'),
    path('new/', AskQuestionView.as_view(), name='ask'),
    path('question/<int:pk>/', QuestionView.as_view(), name='question'),
    path('vote_up_<str:object_type>_<int:obj_id>/', VoteView.as_view(vote_up=True), name='vote_up'),
    path('vote_down_<str:object_type>_<int:obj_id>/', VoteView.as_view(vote_up=False), name='vote_down'),
    path('mark_<int:answer_id>_<int:question_id>/', MarkCorrectAnswerView.as_view(), name='correct_answer'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
]

users/urls.py
from django.urls import path
from .views import SignUpView, CustomLoginView, ChangeProfileView
from django.contrib.auth.views import LogoutView


app_name = 'users'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', CustomLoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(next_page='index'), name='logout'),
    path('settings/', ChangeProfileView.as_view(), name='settings'),
]

templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'questions:index' '-created_date' %}">HASKER</a>
    <ul class="navbar-nav ml-auto">
      <form class="form-inline my-2 my-lg-0" action="{% url 'questions:search_results' %}" method="get">
        <input class="form-control mr-sm-2" type="search" placeholder="Search..." aria-label="Search" name="q">
      </form>
      <img src="{{ user.userprofile.image_url }}" width="40" height="40" alt="">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:settings' %}">{{ user.username }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">Log Out</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:signup' %}">Sign Up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:login' %}">Log In</a>
        </li>
      {% endif %}
    </ul>
</nav>

templates/_sidebar.html
{% block sidebar %}
    <p class="break"></p>
    <div class="col-md-3 float-right">
        <div class="ml-auto card w-40">
            <div class="card-body">
                <table class="table table-borderless">
                    <tr>
                        <td class="align-bottom text-left"><h5>Trending</h5></td>
                        {% if user.is_authenticated %}
                            <td class="text-right"><a class="btn btn-secondary btn-sm" href="{% url 'questions:ask' %}">Ask!</a></td>
                        {% endif %}
                    </tr>
                </table>
                <table>
                {% for question in trending_questions %}
                    <tr height="50px">
                        <td class="align-top">
                            <button type="button" class="btn btn-secondary color-red">{{question.votes}}</button>
                        </td>
                        <td width="5px"></td>
                        <td class="align-center">
                            <a class="text-small" href="{% url 'questions:question' question.id %}">{{question.header|truncatechars:100}}</a>
                        </td>
                    </tr>
                {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock sidebar %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
        <title>
            {% block title %}
            {% endblock title %}
        </title>
    </head>
    <body>
        {% include '_navbar.html' %}
        <div class="row justify-content-center">
            <div class="col-10">
                {% include '_sidebar.html' %}
                {% block content %}
                    <p>Placeholder text in base template. Replace with page content.</p>
                {% endblock content %}
            </div>
        </div>
    </body>
</html>